## Numpy 

provides support for matrix and arrays with many fns for calculations

In [5]:
import numpy as np

arr1 = np.array([1, 2, 3])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3]
<class 'numpy.ndarray'>
(3,)


In [11]:
arr2 = np.array([1, 2, 3, 4, 5])
arr2 = arr2.reshape(1, 5)
print(arr2)

[[1 2 3 4 5]]


In [14]:
arr2 = np.array([[1, 2, 3, 4, 5]])
arr2.shape

(1, 5)

In [19]:
## 2d array
arr2 = np.array([[1, 2, 3, 4, 5], [2, 3, 4, 5, 6]])
print(arr2)
print(arr2.shape)

[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)


In [23]:
np.arange(0, 10, 2).reshape(5, 1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [26]:
np.ones((3, 4))  # Create a 3x4 array of ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [28]:
## identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [32]:
## Attributes of numpy array

arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
print("Shape:", arr.shape)
print("Number of dimensions:", arr.ndim)
print("Data type:", arr.dtype)
print("Total number of elements:", arr.size)
print("Size of each element in bytes:", arr.itemsize)

[[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of dimensions: 2
Data type: int32
Total number of elements: 6
Size of each element in bytes: 4


In [34]:
## numpy vectorized operation
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([10, 20, 30, 40, 50])

# Element-wise addition
print("Element-wise addition:", arr1 + arr2)

# Element-wise subtraction
print("Element-wise subtraction:", arr1 - arr2)

# Element-wise multiplication
print("Element-wise multiplication:", arr1 * arr2)

# Element-wise division
print("Element-wise division:", arr1 / arr2)


Element-wise addition: [11 22 33 44 55]
Element-wise subtraction: [ -9 -18 -27 -36 -45]
Element-wise multiplication: [ 10  40  90 160 250]
Element-wise division: [0.1 0.1 0.1 0.1 0.1]


In [36]:
# Universal functions
arr = np.array([1, 2, 3, 4, 5])

# Square root
print("Square root:", np.sqrt(arr))

## Exponential
print("Exponential:", np.exp(arr))

## Sine
print("Sine:", np.sin(arr))

## natural log
print("Natural log:", np.log(arr))

Square root: [1.         1.41421356 1.73205081 2.         2.23606798]
Exponential: [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
Sine: [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
Natural log: [0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [38]:
## Universal funcitons(ufuncs)

# array slicing and indexing
arr=np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [48]:
# accessing a specific element
arr[0][0] 
#or arr[0, 0]
print(arr[0:2,2:])

[[3 4]
 [7 8]]


In [46]:
arr[1:,2:]

array([[ 7,  8],
       [11, 12]])

In [56]:
print(arr[1:, 1:3])

[[ 6  7]
 [10 11]]


In [58]:
# Modify array elements
arr[0, 0]= 100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [60]:
arr[1:] = 100
print(arr)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [62]:
# statistical concepts -- normalizaiton
## to have a mean of 0 and a standard deviation of 1
data = np.array([1, 2, 3, 4, 5])

#calcualte the mean and the standard deviation
mean = np.mean(data)
std_dev = np.std(data)

# Normalize the data
normalized_data = (data - mean) / std_dev
print("Original data:", data)
print("Mean:", mean)
print("Standard Deviation:", std_dev)
print("Normalized data:", normalized_data)

Original data: [1 2 3 4 5]
Mean: 3.0
Standard Deviation: 1.4142135623730951
Normalized data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [69]:
## logical operation 
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
data[(data>5) & (data<=8)]

array([6, 7, 8])